'use strict';
const KEY='renewalflow_data_v3', AUTH='renewalflow_auth'; let data=loadData();
const $=id=>document.getElementById(id); const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d;};
function loadData(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}} function save(){localStorage.setItem(KEY,JSON.stringify(data));render()} function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function days(s){return Math.ceil((new Date(s+'T00:00:00')-today())/86400000)} function prettyDate(s){return new Date(s+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})} function money(n){return n?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n):'—'}
function initials(n){return(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()} function status(d){if(d<0)return['overdue',Math.abs(d)+'d overdue'];if(d===0)return['today','Due today'];if(d<=7)return['soon','Due in '+d+'d'];return['later','Due in '+d+'d']}
function cleanPhone(p){return String(p||'').replace(/\D/g,'')} function whatsappPhone(p){let n=cleanPhone(p);if(n.length===10)n='91'+n;return n}
function message(r){return`Hello ${r.name}, your ${(r.type||'insurance').toLowerCase()} insurance renewal is due on ${prettyDate(r.date)}. Please contact me if you would like assistance with the renewal.`}
function openExternal(url){const w=window.open(url,'_blank','noopener,noreferrer');if(!w)location.href=url}
function openWhatsApp(r){const n=whatsappPhone(r.phone);if(n.length<11){alert('Please enter a valid WhatsApp number. Use 10 digits or include country code.');return}openExternal(`https://wa.me/${n}?text=${encodeURIComponent(message(r))}`)}
function calendarUrl(r){const pad=n=>String(n).padStart(2,'0');const [y,m,d]=r.date.split('-').map(Number);const[hh,mm]='08:30'.split(':').map(Number);const start=`${y}${pad(m)}${pad(d)}T${pad(hh)}${pad(mm)}00`;const e=new Date(y,m-1,d,hh,mm);e.setMinutes(e.getMinutes()+30);const end=`${e.getFullYear()}${pad(e.getMonth()+1)}${pad(e.getDate())}T${pad(e.getHours())}${pad(e.getMinutes())}00`;const u=new URL('https://calendar.google.com/calendar/render');u.searchParams.set('action','TEMPLATE');u.searchParams.set('text',`Insurance Renewal — ${r.name}`);u.searchParams.set('dates',`${start}/${end}`);u.searchParams.set('details',`${message(r)}\n\nCreated from RenewalFlow.`);return u.toString()}
function openCalendar(r){openExternal(calendarUrl(r))}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){if($('app').classList.contains('hidden'))return;const all=data.filter(x=>x&&x.date),q=($('search').value||'').toLowerCase().trim(),f=$('filter').value;const overdue=all.filter(x=>days(x.date)<0).length,t=all.filter(x=>days(x.date)===0).length,seven=all.filter(x=>days(x.date)>=0&&days(x.date)<=7).length,thirty=all.filter(x=>days(x.date)>=0&&days(x.date)<=30).length;$('overdue').textContent=overdue;$('today').textContent=t;$('seven').textContent=seven;$('thirty').textContent=thirty;$('heroTotal').textContent=all.length;$('morning').textContent=overdue?`${overdue} overdue renewal${overdue>1?'s':''} need attention first.`:t?`${t} renewal${t>1?'s':''} due today. Start your WhatsApp follow-ups.`:seven?`${seven} priority renewal${seven>1?'s':''} in the next 7 days.`:'No urgent renewals — your pipeline is clear.';const list=all.filter(r=>`${r.name} ${r.type} ${r.phone}`.toLowerCase().includes(q)).filter(r=>{const d=days(r.date);return f==='all'||f==='overdue'&&d<0||f==='today'&&d===0||f==='7'&&d>=0&&d<=7||f==='30'&&d>=0&&d<=30}).sort((a,b)=>new Date(a.date)-new Date(b.date));$('empty').style.display=list.length?'none':'block';$('list').innerHTML=list.map(r=>{const[s,b]=status(days(r.date));return`<article class="card"><div class="client"><div class="avatar">${escapeHtml(initials(r.name))}</div><div><b>${escapeHtml(r.name)}</b><span class="muted">${escapeHtml(r.type)} · ${escapeHtml(r.phone)}</span></div></div><div class="status"><b>${escapeHtml(prettyDate(r.date))}</b><span class="badge ${s}">${escapeHtml(b)}</span></div><div class="cardactions"><button class="mini wa" data-action="wa" data-id="${r.id}" title="Send WhatsApp reminder">☘</button><button class="mini cal" data-action="cal" data-id="${r.id}" title="Add to Google Calendar">📅</button><button class="mini" data-action="edit" data-id="${r.id}" title="Edit renewal" aria-label="Edit renewal">✎</button><button class="mini delete-mini" data-action="delete" data-id="${r.id}" title="Delete renewal" aria-label="Delete renewal">🗑</button></div></article>`}).join('')}
function deleteRenewal(id){const r=data.find(x=>x.id===id);if(!r)return;if(confirm(`Delete ${r.name}'s renewal record? This cannot be undone.`)){data=data.filter(x=>x.id!==id);save();}}
function openForm(r=null){$('form').reset();$('id').value=r?.id||'';$('modalTitle').textContent=r?'Edit Renewal':'Add Renewal';$('name').value=r?.name||'';$('phone').value=r?.phone||'';$('type').value=r?.type||'Life Insurance';$('date').value=r?.date||new Date().toISOString().slice(0,10);$('del').classList.toggle('hidden',!r);updatePreview();$('dlg').showModal();$('name').focus()}
function updatePreview(){const r={name:$('name').value||'Customer',type:$('type').value,date:$('date').value||new Date().toISOString().slice(0,10)};$('preview').textContent=message(r)}
function priorityRows(){return data.filter(r=>{const d=days(r.date);return d<0||d<=7}).sort((a,b)=>new Date(a.date)-new Date(b.date))}
function downloadBlob(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function csvExport(){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const head=['Name','WhatsApp Number','Insurance Type','Renewal Date'];downloadBlob([head.map(q).join(','),...data.map(r=>[r.name,r.phone,r.type,r.date].map(q).join(','))].join('\n'),'renewalflow-policies.csv','text/csv')}
function loadDemo(){const base=today(),plus=n=>{const x=new Date(base);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};data.push({id:uid(),name:'Aarav Mehta',phone:'9876543210',type:'Health Insurance',date:plus(0)},{id:uid(),name:'Neha Kapoor',phone:'9810123456',type:'Motor Insurance',date:plus(3)});save()}
function login(){if($('loginUser').value==='Rajesh'&&$('loginPass').value==='Rajesh7107'){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');sessionStorage.setItem(AUTH,'1');$('loginError').textContent='';render()}else $('loginError').textContent='Invalid username or password.'}
$('loginForm').addEventListener('submit',e=>{e.preventDefault();login()});$('logout').addEventListener('click',()=>{sessionStorage.removeItem(AUTH);$('app').classList.add('hidden');$('loginScreen').classList.remove('hidden');$('loginPass').value=''});
if(sessionStorage.getItem(AUTH)==='1'){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden')}
['add','add2','add3'].forEach(id=>$(id).addEventListener('click',()=>openForm()));$('cancel').addEventListener('click',()=>$('dlg').close());$('x').addEventListener('click',()=>$('dlg').close());['name','date','type'].forEach(id=>$(id).addEventListener('input',updatePreview));$('phone').addEventListener('input',updatePreview);
$('form').addEventListener('submit',e=>{e.preventDefault();const id=$('id').value;const r={id:id||uid(),name:$('name').value.trim(),phone:$('phone').value.trim(),type:$('type').value,date:$('date').value};if(!r.name||!r.phone||!r.date)return;const i=data.findIndex(x=>x.id===id);if(i>=0)data[i]=r;else data.push(r);save();$('dlg').close()});
$('del').addEventListener('click',()=>{const id=$('id').value;if(id&&confirm('Delete this renewal?')){data=data.filter(x=>x.id!==id);save();$('dlg').close()}});$('list').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const r=data.find(x=>x.id===b.dataset.id);if(!r)return;if(b.dataset.action==='wa')openWhatsApp(r);if(b.dataset.action==='cal')openCalendar(r);if(b.dataset.action==='edit')openForm(r);if(b.dataset.action==='delete')deleteRenewal(r.id)});
$('search').addEventListener('input',render);$('filter').addEventListener('change',render);$('priority').addEventListener('click',()=>{$('filter').value='7';render();window.scrollTo({top:$('list').offsetTop-20,behavior:'smooth'})});$('backup').addEventListener('click',()=>downloadBlob(JSON.stringify(data,null,2),'renewalflow-backup.json','application/json'));$('import').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!Array.isArray(x))throw Error();if(confirm('Replace current renewals with this backup?')){data=x;save()}}catch{alert('Invalid backup file.')}e.target.value=''};rd.readAsText(f)});
$('bell').addEventListener('click',async()=>{if(!('Notification'in window))return alert('Browser notifications are not supported.');const p=await Notification.requestPermission();if(p==='granted')new Notification('RenewalFlow',{body:'Browser reminders are enabled. WhatsApp messages require a click to send.'})});
render();
